# "/" + ä»“åº“çš„åå­—. èµ„æºæ–‡ä»¶çš„è·¯å¾„ç»„æˆéƒ¨åˆ†
baseurl: "/baseball4"

# ç½‘é¡µçš„æ ‡é¢˜
title: "æ£’çƒå°‘å¥³æµ·æ¥é‡‘é‡Œ"
username: sarah
# ç½‘ç«™å‰¯æ ‡é¢˜
description: "å°å°æ£’çƒå¼€å¯æ”¹å˜è´«å›°çš„å¥‘æœº"

aboutme: "Sarah ğŸ˜‰ğŸ•ğŸ§"

# å…¶å®ƒé…ç½®, å¯å¿½ç•¥, æ— éœ€ä¿®æ”¹
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
permalink: /:title/
paginate_path: "/page:num/"
